(function(c){function d(l){var s=l.data("width"),h=l.data("height"),q=l.data("youtube-id"),i=l.data("parameters")||"";if(typeof s==="undefined"||typeof h==="undefined"||typeof q==="undefined")throw Error("lazyYT is missing a required data attribute.");l.css({position:"relative",height:h,width:s,background:"url(http://img.youtube.com/vi/"+q+"/maxresdefault.jpg) center center no-repeat",cursor:"pointer","-webkit-background-size":"cover","-moz-background-size":"cover","-o-background-size":"cover","background-size":"cover"}).html('<p id="lazyYT-title-'+
q+'" class="lazyYT-title"></p><div class="lazyYT-button"></div>').addClass("lazyYT-image-loaded");c.getJSON("https://gdata.youtube.com/feeds/api/videos/"+q+"?v=2&alt=json",function(r){c("#lazyYT-title-"+q).text(r.entry.title.$t)});l.on("click",function(r){r.preventDefault();!l.hasClass("lazyYT-video-loaded")&&l.hasClass("lazyYT-image-loaded")&&l.html('<iframe width="'+s+'" height="'+h+'" src="//www.youtube.com/embed/'+q+"?autoplay=1&"+i+'" frameborder="0" allowfullscreen></iframe>').removeClass("lazyYT-image-loaded").addClass("lazyYT-video-loaded")})}
c.fn.lazyYT=function(){return this.each(function(){var l=c(this).css("cursor","pointer");d(l)})}})(jQuery);
function Swipe(c,d){function l(){j=g.children;B=j.length;if(j.length<2)d.continuous=false;if(t.transitions&&d.continuous&&j.length<3){g.appendChild(j[0].cloneNode(true));g.appendChild(g.children[1].cloneNode(true));j=g.children}o=Array(j.length);f=c.getBoundingClientRect().width||c.offsetWidth;g.style.width=j.length*f+"px";for(var a=j.length;a--;){var e=j[a];e.style.width=f+"px";e.setAttribute("data-index",a);if(t.transitions){e.style.left=a*-f+"px";i(a,b>a?-f:b<a?f:0,0)}}if(d.continuous&&t.transitions){i(h(b-
1),-f,0);i(h(b+1),f,0)}if(!t.transitions)g.style.left=b*-f+"px";c.style.visibility="visible"}function s(){if(d.continuous)q(b+1);else b<j.length-1&&q(b+1)}function h(a){return(j.length+a%j.length)%j.length}function q(a,e){if(b!=a){if(t.transitions){var k=Math.abs(b-a)/(b-a);if(d.continuous){var v=k;k=-o[h(a)]/f;if(k!==v)a=-k*j.length+a}for(v=Math.abs(b-a)-1;v--;)i(h((a>b?a:b)-v-1),f*k,0);a=h(a);i(b,f*k,e||p);i(a,0,e||p);d.continuous&&i(h(a-k),-(f*k),0)}else{a=h(a);D(b*-f,a*-f,e||p)}b=a;k=d.callback&&
d.callback(b,j[b]);setTimeout(k||y,0)}}function i(a,e,k){r(a,e,k);o[a]=e}function r(a,e,k){if(a=(a=j[a])&&a.style){a.webkitTransitionDuration=a.MozTransitionDuration=a.msTransitionDuration=a.OTransitionDuration=a.transitionDuration=k+"ms";a.webkitTransform="translate("+e+"px,0)translateZ(0)";a.msTransform=a.MozTransform=a.OTransform="translateX("+e+"px)"}}function D(a,e,k){if(k)var v=+new Date,E=setInterval(function(){var C=+new Date-v;if(C>k){g.style.left=e+"px";if(u)z=setTimeout(s,u);d.transitionEnd&&
d.transitionEnd.call(event,b,j[b]);clearInterval(E)}else g.style.left=(e-a)*(Math.floor(C/k*100)/100)+a+"px"},4);else g.style.left=e+"px"}function x(){u=0;clearTimeout(z)}var y=function(){},t={addEventListener:!!window.addEventListener,touch:"ontouchstart"in window||window.DocumentTouch&&document instanceof DocumentTouch,transitions:function(a){var e=["transitionProperty","WebkitTransition","MozTransition","OTransition","msTransition"],k;for(k in e)if(a.style[e[k]]!==undefined)return true;return false}(document.createElement("swipe"))};
if(c){var g=c.children[0],j,o,f,B;d=d||{};var b=parseInt(d.startSlide,10)||0,p=d.speed||300;d.continuous=d.continuous!==undefined?d.continuous:true;var u=d.auto||0,z,A={},m={},w,n={handleEvent:function(a){switch(a.type){case "touchstart":this.start(a);break;case "touchmove":this.move(a);break;case "touchend":var e=this.end(a);setTimeout(e||y,0);break;case "webkitTransitionEnd":case "msTransitionEnd":case "oTransitionEnd":case "otransitionend":case "transitionend":e=this.transitionEnd(a);setTimeout(e||
y,0);break;case "resize":e=l.call();setTimeout(e||y,0)}d.stopPropagation&&a.stopPropagation()},start:function(a){a=a.touches[0];A={x:a.pageX,y:a.pageY,time:+new Date};w=undefined;m={};g.addEventListener("touchmove",this,false);g.addEventListener("touchend",this,false)},move:function(a){if(!(a.touches.length>1||a.scale&&a.scale!==1)){d.disableScroll&&a.preventDefault();var e=a.touches[0];m={x:e.pageX-A.x,y:e.pageY-A.y};if(typeof w=="undefined")w=!!(w||Math.abs(m.x)<Math.abs(m.y));if(!w){a.preventDefault();
x();if(d.continuous){r(h(b-1),m.x+o[h(b-1)],0);r(b,m.x+o[b],0);r(h(b+1),m.x+o[h(b+1)],0)}else{m.x/=!b&&m.x>0||b==j.length-1&&m.x<0?Math.abs(m.x)/f+1:1;r(b-1,m.x+o[b-1],0);r(b,m.x+o[b],0);r(b+1,m.x+o[b+1],0)}}}},end:function(){var a=Number(+new Date-A.time)<250&&Math.abs(m.x)>20||Math.abs(m.x)>f/2,e=!b&&m.x>0||b==j.length-1&&m.x<0;if(d.continuous)e=false;var k=m.x<0;if(!w)if(a&&!e){if(k){if(d.continuous){i(h(b-1),-f,0);i(h(b+2),f,0)}else i(b-1,-f,0);i(b,o[b]-f,p);i(h(b+1),o[h(b+1)]-f,p);b=h(b+1)}else{if(d.continuous){i(h(b+
1),f,0);i(h(b-2),-f,0)}else i(b+1,f,0);i(b,o[b]+f,p);i(h(b-1),o[h(b-1)]+f,p);b=h(b-1)}d.callback&&d.callback(b,j[b])}else if(d.continuous){i(h(b-1),-f,p);i(b,0,p);i(h(b+1),f,p)}else{i(b-1,-f,p);i(b,0,p);i(b+1,f,p)}g.removeEventListener("touchmove",n,false);g.removeEventListener("touchend",n,false)},transitionEnd:function(a){if(parseInt(a.target.getAttribute("data-index"),10)==b){if(u)z=setTimeout(s,u);d.transitionEnd&&d.transitionEnd.call(a,b,j[b])}}};l();if(u)z=setTimeout(s,u);if(t.addEventListener){t.touch&&
g.addEventListener("touchstart",n,false);if(t.transitions){g.addEventListener("webkitTransitionEnd",n,false);g.addEventListener("msTransitionEnd",n,false);g.addEventListener("oTransitionEnd",n,false);g.addEventListener("otransitionend",n,false);g.addEventListener("transitionend",n,false)}window.addEventListener("resize",n,false)}else window.onresize=function(){l()};return{setup:function(){l()},slide:function(a,e){x();q(a,e)},prev:function(){x();if(d.continuous)q(b-1);else b&&q(b-1)},next:function(){x();
s()},getPos:function(){return b},getNumSlides:function(){return B},kill:function(){x();g.style.width="auto";g.style.left=0;for(var a=j.length;a--;){var e=j[a];e.style.width="100%";e.style.left=0;t.transitions&&r(a,0,0)}if(t.addEventListener){g.removeEventListener("touchstart",n,false);g.removeEventListener("webkitTransitionEnd",n,false);g.removeEventListener("msTransitionEnd",n,false);g.removeEventListener("oTransitionEnd",n,false);g.removeEventListener("otransitionend",n,false);g.removeEventListener("transitionend",
n,false);window.removeEventListener("resize",n,false)}else window.onresize=null}}}}if(window.jQuery||window.Zepto)(function(c){c.fn.Swipe=function(d){return this.each(function(){c(this).data("Swipe",new Swipe(c(this)[0],d))})}})(window.jQuery||window.Zepto);
$(function(){$("form *[data-placeholder]").each(function(){var c=$(this),d=$(this).data("placeholder");c.on("phfocus",function(){c.val()==d&&c.val("").removeClass("placeheld")}).focus(function(){c.trigger("phfocus")}).on("phblur",function(){c.val()==""&&c.val(d).addClass("placeheld")}).blur(function(){c.trigger("phblur")});c.trigger("phblur")})});
$(function(){$(".mobiletoggle").click(function(){$("#header").toggleClass("open")});$("#nav ul li ul").click(function(){$(this).toggleClass("open")});var c=function(){$(window).scrollTop()>120?$("html").addClass("scrolled"):$("html").removeClass("scrolled")};$(window).scroll(function(){c()});c()});
$(function(){$(".lazyYT").lazyYT();$(".swipe").each(function(){var c=$(this);c.find(".swipe-wrap>div").eq(0).addClass("active");c.find(".direct a").eq(0).addClass("active");var d=c.data("auto")?c.data("auto"):8E3,l=new Swipe(c[0],{startSlide:0,speed:400,auto:d,continuous:true,disableScroll:false,stopPropagation:false,callback:function(s){c.find(".active").addClass("outgoing").removeClass("active");c.find(".slide").eq(s).addClass("incoming");c.find(".direct a").eq(s).addClass("incoming")},transitionEnd:function(){c.find(".incoming").addClass("active").removeClass("incoming");
c.find(".outgoing").removeClass("outgoing")}});c.find(".next").click(function(){l.next()});c.find(".prev").click(function(){l.prev()});c.find(".direct a").click(function(){l.slide($(this).data("slide")-1)})})});
